# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from pb import service_pb2 as pb_dot_service__pb2


class HelloServiceStub(object):
  """Hello service responds to incoming hello requests.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Hello = channel.unary_unary(
        '/hello.HelloService/Hello',
        request_serializer=pb_dot_service__pb2.Message.SerializeToString,
        response_deserializer=pb_dot_service__pb2.Message.FromString,
        )


class HelloServiceServicer(object):
  """Hello service responds to incoming hello requests.
  """

  def Hello(self, request, context):
    """Hello method receives a simple message and returns it.
    The message posted as the id parameter will also be returned.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HelloServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Hello': grpc.unary_unary_rpc_method_handler(
          servicer.Hello,
          request_deserializer=pb_dot_service__pb2.Message.FromString,
          response_serializer=pb_dot_service__pb2.Message.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'hello.HelloService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
